#!/usr/bin/env tsx
/**
 * Extracts per-field `.describe(...)` text from each request schema in
 * src/api/schemas.ts and emits a static
 * `public/builder/js/command-descriptions.js` so the Sequence Builder
 * can show the schema text as hover-tooltips on every field label
 * without a runtime fetch.
 *
 * One source of truth: the Zod schemas already used by the API.
 *
 * Wired to `prebuild` and the `pre*-server` lifecycle hooks via
 * package.json — same pattern as scripts/build-version.cjs.
 */

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { z } from "@hono/zod-openapi"

import { commandConfigs } from "../src/api/routes/commandRoutes.js"

const repoRoot = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../..",
)

// Legacy HTML builder location (still served at /builder/ by the API).
const legacyOutputPath = join(
  repoRoot,
  "public",
  "builder",
  "js",
  "command-descriptions.js",
)

// React web app location — Vite's `publicDir` defaults to
// packages/web/public/, which is copied to dist/ at build time. The
// React index.html loads /command-descriptions.js so window.getCommandFieldDescription
// is defined before the SPA reads it (CommandFieldEntry, FieldTooltip).
const webOutputPath = join(
  repoRoot,
  "packages",
  "web",
  "public",
  "command-descriptions.js",
)

// Walk through any wrapper schemas (default/optional/nullable/preprocess)
// to reach the underlying schema and its registry-stored description.
const unwrap = (schema: z.ZodTypeAny): z.ZodTypeAny => {
  const definition = schema._def as
    | { innerType?: z.ZodTypeAny; schema?: z.ZodTypeAny }
    | undefined

  if (!definition) {
    return schema
  }

  if (definition.innerType) {
    return unwrap(definition.innerType)
  }

  if (definition.schema) {
    return unwrap(definition.schema)
  }

  return schema
}

const getDescriptionForSchema = (
  schema: z.ZodTypeAny,
): string | null => {
  const directMeta = z.globalRegistry.get(schema) as
    | { description?: string }
    | undefined

  if (directMeta?.description) {
    return directMeta.description
  }

  const unwrapped = unwrap(schema)
  const unwrappedMeta = z.globalRegistry.get(unwrapped) as
    | { description?: string }
    | undefined

  if (unwrappedMeta?.description) {
    return unwrappedMeta.description
  }

  return null
}

const collectFieldDescriptions = (
  schema: z.ZodTypeAny,
): Record<string, string> => {
  const objectSchema = unwrap(schema) as {
    shape?: Record<string, z.ZodTypeAny>
  }

  if (!objectSchema?.shape) {
    return {}
  }

  return Object.entries(objectSchema.shape).reduce(
    (
      accumulator: Record<string, string>,
      [fieldName, fieldSchema],
    ) => {
      const description =
        getDescriptionForSchema(fieldSchema)

      if (description) {
        accumulator[fieldName] = description
      }

      return accumulator
    },
    {} as Record<string, string>,
  )
}

const commandDescriptions = Object.entries(
  commandConfigs,
).reduce(
  (
    accumulator: Record<
      string,
      { summary: string; fields: Record<string, string> }
    >,
    [commandName, configuration],
  ) => {
    const fieldDescriptions = collectFieldDescriptions(
      configuration.schema,
    )
    const summaryDescription = getDescriptionForSchema(
      configuration.schema,
    )

    accumulator[commandName] = {
      summary: summaryDescription ?? configuration.summary,
      fields: fieldDescriptions,
    }

    return accumulator
  },
  {} as Record<
    string,
    { summary: string; fields: Record<string, string> }
  >,
)

const fileBanner = `// Auto-generated by packages/api/scripts/build-command-descriptions.ts.
// DO NOT EDIT BY HAND. Update the per-field .describe(...) calls in
// src/api/schemas.ts instead — the prebuild step regenerates this file
// every time the API server (or build) starts.
//
// Loaded as a plain (non-module) script alongside /command-labels.js so
// the Sequence Builder can show field-level docs as hover tooltips.
// Falls back to an empty object for any command not in the map, so a
// brand-new command never throws when a tooltip is requested before the
// extractor catches up.
`

const fileBody = `${fileBanner}
window.commandDescriptions = ${JSON.stringify(commandDescriptions, null, 2)}

window.getCommandFieldDescription = function getCommandFieldDescription({ commandName, fieldName }) {
  if (!commandName || !fieldName) {
    return ""
  }

  const entry = window.commandDescriptions[commandName]

  if (!entry) {
    return ""
  }

  return entry.fields[fieldName] || ""
}

window.getCommandSummary = function getCommandSummary({ commandName }) {
  if (!commandName) {
    return ""
  }

  const entry = window.commandDescriptions[commandName]

  if (!entry) {
    return ""
  }

  return entry.summary || ""
}
`

const writeOutput = (path: string): void => {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, fileBody, "utf8")
}

writeOutput(legacyOutputPath)
writeOutput(webOutputPath)

const commandCount = Object.keys(commandDescriptions).length
const fieldCount = Object.values(
  commandDescriptions,
).reduce(
  (total, entry) =>
    total + Object.keys(entry.fields).length,
  0,
)

console.log(
  `[build-command-descriptions] wrote ${legacyOutputPath} + ${webOutputPath} (${commandCount} commands, ${fieldCount} described fields)`,
)
