// Single source of truth for the set of commands the server registers.
// Extracted to its own file (no Node-side imports) so it can be imported
// from browser-mode vitest in packages/web — the registry-sync test in
// packages/web/src/commands/commands.test.ts asserts this list matches
// the web COMMANDS map and commandLabels keys.
//
// commandRoutes.ts re-exports both `commandNames` and the derived
// `CommandName` type from here so existing call sites keep working.

export const commandNames = [
  "analyseDiscBackup",
  "makeDirectory",
  "matchMusicRelease",
  "matchMusicBrainzRelease",
  "matchDiscogsRelease",
  "matchFreedbRelease",
  "matchVgmdbRelease",
  "changeTrackLanguages",
  "convertLosslessToFlac",
  "convertContainerAudioToFlac",
  "convertSrtToAss",
  "findContainerAudioFiles",
  "copyFiles",
  "flattenOutput",
  "copyOutSubtitles",
  "extractDiscTitles",
  "extractSubtitles",
  "fixIncorrectDefaultTracks",
  "getAudioOffsets",
  "hasBetterAudio",
  "hasBetterVersion",
  "hasDuplicateMusicFiles",
  "hasImaxEnhancedAudio",
  "hasManyAudioTracks",
  "hasSurroundSound",
  "hasWrongDefaultTrack",
  "isMissingSubtitles",
  "deleteCopiedOriginals",
  "deleteFilesByExtension",
  "deleteFolder",
  "exitIfEmpty",
  "modifySubtitleMetadata",
  "keepLanguages",
  "addSubtitles",
  "mergeTracks",
  "moveFiles",
  "moveFilesIntoNamedFolders",
  "distributeFolderToSiblings",
  "flattenChildFolders",
  "renameFiles",
  "renameFilesAndFolders",
  "nameAnimeEpisodes",
  "nameAnimeEpisodesAniDB",
  "fetchThemeMusic",
  "nameMovieCutsDvdCompareTmdb",
  "nameSpecialFeaturesDvdCompareTmdb",
  "onlyNameSpecialFeaturesDvdCompare",
  "nameTvShowEpisodes",
  "remuxToMkv",
  "fingerprintAudioFiles",
  "findDuplicateAudioFiles",
  "compareMusicAssistantLibrary",
  "scanAudioFiles",
  "copyAudioReleaseDateIntoDate",
  "renumberChapters",
  "renameAndMoveAudioFiles",
  "renameDemos",
  "renameMovieClipDownloads",
  "reorderTracks",
  "replaceAttachments",
  "replaceFlacWithPcmAudio",
  "replaceTracks",
  "setDisplayWidth",
  "splitChapters",
  "splitCueSheet",
  "storeAspectRatioData",
  "writeAudioTags",
] as const

export type CommandName = (typeof commandNames)[number]
