import { describe, expect, test } from "vitest"

import { applyAssRules } from "./applyAssRules.js"
import {
  parseAssFile,
  serializeAssFile,
} from "./assFileTools.js"

const SAMPLE_1 = `[Script Info]
Title: Un-fuck CR Style (TH)
WrapStyle: 0
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
PlayResX: 640
PlayResY: 360
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Trebuchet MS,24,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,18,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:12.96,0:00:16.21,Default,,0,0,0,,Rider...
Dialogue: 0,0:00:23.96,0:00:27.92,Default,,0,0,0,,{\\i1}I've always loved Kamen Rider,{\\i0}\\N{\\i1}ever since I was a kid.{\\i0}`

const SAMPLE_2 = `[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Crunchyroll Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 640
PlayResY: 360
LayoutResX: 640
LayoutResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Gandhi Sans,24,&H00FFFFFF,&H000000FF,&H00000000,&HA0000000,-1,0,0,0,100,100,0,0,1,1.2,0.5,2,10,10,20,1
Style: Top,Gandhi Sans,24,&H00FFFFFF,&H000000FF,&H00000000,&HA0000000,-1,0,0,0,100,100,0,0,1,1.2,0.5,8,10,10,20,1
Style: Italics,Gandhi Sans,24,&H00FFFFFF,&H000000FF,&H00000000,&HA0000000,-1,-1,0,0,100,100,0,0,1,1.2,0.5,2,10,10,20,0
Style: Signs,Arial,22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,8,10,10,20,1
Style: Flashback,Gandhi Sans,24,&H00F7ECEB,&H000000FF,&H004D0701,&HA0000000,-1,0,0,0,100,100,0,0,1,1.2,0.5,2,10,10,20,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:22.59,0:00:23.63,Default,Tojima,0,0,0,,Let's go!
Dialogue: 0,0:00:28.28,0:00:31.64,Default,Yukarisu,0,0,0,,You're already torn up. \\NYou sure about this?`

const SAMPLE_POSITIONED = `[Script Info]
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 640
PlayResY: 480
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,30,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,2,0,1,2,1,2,10,10,15,0
Style: Nameplate,Arial,30,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:25.98,0:00:29.94,Nameplate,,0,0,0,,{\\pos(319,450)}Preta Quoiz
Dialogue: 0,0:00:30.00,0:00:34.00,Default,,0,0,0,,{\\move(100,200,300,400,0,900)}Sliding sign
Dialogue: 0,0:00:35.00,0:00:39.00,Default,,0,0,0,,{\\clip(10,20,30,40)}Boxed
Dialogue: 0,0:00:40.00,0:00:44.00,Default,,0,0,0,,{\\clip(m 0 0 l 100 0 100 100 0 100)}Drawn
Dialogue: 0,0:00:45.00,0:00:49.00,Default,,0,0,0,,{\\fs30\\bord2\\shad1\\fsp4\\xbord3\\org(320,240)}Sized
Dialogue: 0,0:00:50.00,0:00:54.00,Default,,0,0,0,,Plain dialogue with no tags`

// Helper to get a Script Info property value
const getScriptInfoValue = (
  content: string,
  key: string,
) => {
  const parsed = parseAssFile(content)
  const section = parsed.sections.find(
    (section) => section.sectionType === "scriptInfo",
  )
  if (section?.sectionType !== "scriptInfo")
    return undefined
  const entry = section.entries.find(
    (entry) =>
      entry.type === "property" && entry.key === key,
  )
  return entry?.type === "property"
    ? entry.value
    : undefined
}

describe("parseAssFile", () => {
  test("parses Script Info properties correctly", () => {
    const result = parseAssFile(SAMPLE_1)
    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    expect(section?.sectionType).toBe("scriptInfo")
    if (section?.sectionType !== "scriptInfo") return

    expect(
      section.entries.find(
        (entry) =>
          entry.type === "property" &&
          entry.key === "PlayResX",
      ),
    ).toEqual({
      type: "property",
      key: "PlayResX",
      value: "640",
    })

    expect(
      section.entries.find(
        (entry) =>
          entry.type === "property" &&
          entry.key === "YCbCr Matrix",
      ),
    ).toEqual({
      type: "property",
      key: "YCbCr Matrix",
      value: "TV.709",
    })
  })

  test("preserves Script Info comments in order", () => {
    const result = parseAssFile(SAMPLE_2)
    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return

    expect(section.entries[0]).toEqual({
      type: "comment",
      text: "; Script generated by Aegisub 3.2.2",
    })
    expect(section.entries[1]).toEqual({
      type: "comment",
      text: "; http://www.aegisub.org/",
    })
  })

  test("parses V4+ Styles format fields by name", () => {
    const result = parseAssFile(SAMPLE_1)
    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    expect(section?.sectionType).toBe("formatted")
    if (section?.sectionType !== "formatted") return

    expect(section.entries).toHaveLength(1)
    const style = section.entries[0]
    expect(style.entryType).toBe("Style")
    expect(style.fields.Name).toBe("Default")
    expect(style.fields.Fontname).toBe("Trebuchet MS")
    expect(style.fields.MarginL).toBe("10")
    expect(style.fields.MarginR).toBe("10")
    expect(style.fields.MarginV).toBe("18")
    expect(style.fields.Encoding).toBe("0")
  })

  test("handles commas inside the Text field of Events entries", () => {
    const result = parseAssFile(SAMPLE_1)
    const events = result.sections.find(
      (section) => section.sectionName === "Events",
    )
    if (events?.sectionType !== "formatted") return

    const dialogueWithComma = events.entries.find((entry) =>
      entry.fields.Text?.includes(","),
    )
    expect(dialogueWithComma?.fields.Text).toBe(
      "{\\i1}I've always loved Kamen Rider,{\\i0}\\N{\\i1}ever since I was a kid.{\\i0}",
    )
    expect(dialogueWithComma?.fields.Layer).toBe("0")
    expect(dialogueWithComma?.fields.Style).toBe("Default")
  })

  test("strips UTF-8 BOM so [Script Info] section is not lost", () => {
    const withBom = `﻿${SAMPLE_1}`
    const result = parseAssFile(withBom)
    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    expect(section?.sectionType).toBe("scriptInfo")
    if (section?.sectionType !== "scriptInfo") return
    expect(
      section.entries.find(
        (entry) =>
          entry.type === "property" &&
          entry.key === "PlayResX",
      ),
    ).toEqual({
      type: "property",
      key: "PlayResX",
      value: "640",
    })
  })

  test("round-trip: parse → serialize → parse produces same structure", () => {
    const parsed1 = parseAssFile(SAMPLE_1)
    const serialized = serializeAssFile(parsed1)
    const parsed2 = parseAssFile(serialized)

    expect(parsed2.sections.length).toBe(
      parsed1.sections.length,
    )

    parsed1.sections.forEach((section, idx) => {
      expect(parsed2.sections[idx].sectionName).toBe(
        section.sectionName,
      )
      expect(parsed2.sections[idx].sectionType).toBe(
        section.sectionType,
      )

      if (
        section.sectionType === "scriptInfo" &&
        parsed2.sections[idx].sectionType === "scriptInfo"
      ) {
        expect(parsed2.sections[idx].entries).toEqual(
          section.entries,
        )
      }

      if (
        section.sectionType === "formatted" &&
        parsed2.sections[idx].sectionType === "formatted"
      ) {
        expect(parsed2.sections[idx].entries).toEqual(
          section.entries,
        )
      }
    })
  })
})

describe("applyAssRules — setScriptInfo", () => {
  test("changes YCbCr Matrix: TV.601 to TV.709", () => {
    const input = SAMPLE_1.replace(
      "YCbCr Matrix: TV.709",
      "YCbCr Matrix: TV.601",
    )
    const parsed = parseAssFile(input)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setScriptInfo",
          key: "YCbCr Matrix",
          value: "TV.709",
        },
      ],
    })

    expect(
      getScriptInfoValue(
        serializeAssFile(result),
        "YCbCr Matrix",
      ),
    ).toBe("TV.709")
  })

  test("changes ScriptType: 3.2.2 to v4.00+", () => {
    const input = SAMPLE_2.replace(
      "ScriptType: v4.00+",
      "ScriptType: 3.2.2",
    )
    const parsed = parseAssFile(input)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setScriptInfo",
          key: "ScriptType",
          value: "v4.00+",
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const entry = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "ScriptType",
    )
    expect(entry).toEqual({
      type: "property",
      key: "ScriptType",
      value: "v4.00+",
    })
  })

  test("adds a key if it doesn't exist", () => {
    const input = SAMPLE_1.replace(
      "\nScaledBorderAndShadow: yes",
      "",
    )
    const parsed = parseAssFile(input)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setScriptInfo",
          key: "ScaledBorderAndShadow",
          value: "yes",
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const entry = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "ScaledBorderAndShadow",
    )
    expect(entry).toEqual({
      type: "property",
      key: "ScaledBorderAndShadow",
      value: "yes",
    })
  })
})

describe("applyAssRules — scaleResolution", () => {
  test("scales PlayResX and PlayResY from 640x360 to 1920x1080", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 360 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const get = (key: string) =>
      section.entries.find(
        (entry) =>
          entry.type === "property" && entry.key === key,
      )

    expect(get("PlayResX")).toEqual({
      type: "property",
      key: "PlayResX",
      value: "1920",
    })
    expect(get("PlayResY")).toEqual({
      type: "property",
      key: "PlayResY",
      value: "1080",
    })
  })

  test("updates existing LayoutResX and LayoutResY", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 360 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const get = (key: string) =>
      section.entries.find(
        (entry) =>
          entry.type === "property" && entry.key === key,
      )

    expect(get("LayoutResX")).toEqual({
      type: "property",
      key: "LayoutResX",
      value: "1920",
    })
    expect(get("LayoutResY")).toEqual({
      type: "property",
      key: "LayoutResY",
      value: "1080",
    })
  })

  test("does not add LayoutResX/Y when absent and addLayoutRes is not set", () => {
    const parsed = parseAssFile(SAMPLE_1)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 360 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return

    const layoutX = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "LayoutResX",
    )
    const layoutY = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "LayoutResY",
    )
    expect(layoutX).toBeUndefined()
    expect(layoutY).toBeUndefined()
  })

  test("adds LayoutResX/Y when absent and addLayoutRes:true", () => {
    const parsed = parseAssFile(SAMPLE_1)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 360 },
          to: { width: 1920, height: 1080 },
          hasLayoutRes: true,
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return

    const layoutX = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "LayoutResX",
    )
    const layoutY = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "LayoutResY",
    )
    expect(layoutX).toEqual({
      type: "property",
      key: "LayoutResX",
      value: "1920",
    })
    expect(layoutY).toEqual({
      type: "property",
      key: "LayoutResY",
      value: "1080",
    })
  })

  test("ensures ScaledBorderAndShadow: yes by default", () => {
    const input = SAMPLE_1.replace(
      "\nScaledBorderAndShadow: yes",
      "",
    )
    const parsed = parseAssFile(input)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 360 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const entry = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "ScaledBorderAndShadow",
    )
    expect(entry).toEqual({
      type: "property",
      key: "ScaledBorderAndShadow",
      value: "yes",
    })
  })

  test("does not scale when source resolution does not match", () => {
    const parsed = parseAssFile(SAMPLE_1)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "scaleResolution",
          from: { width: 1280, height: 720 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionType === "scriptInfo",
    )
    if (section?.sectionType !== "scriptInfo") return
    const playResX = section.entries.find(
      (entry) =>
        entry.type === "property" &&
        entry.key === "PlayResX",
    )
    expect(playResX).toEqual({
      type: "property",
      key: "PlayResX",
      value: "640",
    })
  })
})

describe("applyAssRules — scaleResolution geometry", () => {
  const scaleTo1080 = (
    overrides: Record<string, unknown> = {},
  ) =>
    applyAssRules({
      assFile: parseAssFile(SAMPLE_POSITIONED),
      rules: [
        {
          type: "scaleResolution",
          from: { width: 640, height: 480 },
          to: { width: 1920, height: 1080 },
          ...overrides,
        },
      ],
    })

  const getEventTexts = (
    result: ReturnType<typeof applyAssRules>,
  ) => {
    const section = result.sections.find(
      (section) =>
        section.sectionType === "formatted" &&
        section.entries.some(
          (entry) => entry.entryType === "Dialogue",
        ),
    )
    if (section?.sectionType !== "formatted") {
      return []
    }
    return section.entries.map(
      (entry) => entry.fields.Text ?? "",
    )
  }

  const getStyleRow = (
    result: ReturnType<typeof applyAssRules>,
    styleName: string,
  ) => {
    const section = result.sections.find(
      (section) =>
        section.sectionType === "formatted" &&
        section.entries.some(
          (entry) => entry.entryType === "Style",
        ),
    )
    if (section?.sectionType !== "formatted") {
      return undefined
    }
    return section.entries.find(
      (entry) => entry.fields.Name === styleName,
    )?.fields
  }

  // 640x480 → 1920x1080 is x × 3 and y × 2.25. The two ratios differ, which
  // is the whole reason the tags cannot be left alone.
  test("scales \\pos with the width ratio on x and the height ratio on y", () => {
    expect(getEventTexts(scaleTo1080())[0]).toBe(
      "{\\pos(957,1012.5)}Preta Quoiz",
    )
  })

  test("scales the four \\move coordinates and leaves its two times alone", () => {
    expect(getEventTexts(scaleTo1080())[1]).toBe(
      "{\\move(300,450,900,900,0,900)}Sliding sign",
    )
  })

  test("scales a rectangular \\clip", () => {
    expect(getEventTexts(scaleTo1080())[2]).toBe(
      "{\\clip(30,45,90,90)}Boxed",
    )
  })

  test("leaves a vector-drawing \\clip untouched", () => {
    expect(getEventTexts(scaleTo1080())[3]).toBe(
      "{\\clip(m 0 0 l 100 0 100 100 0 100)}Drawn",
    )
  })

  test("scales the size tags on the correct axis", () => {
    expect(getEventTexts(scaleTo1080())[4]).toBe(
      "{\\fs67.5\\bord4.5\\shad2.25\\fsp12\\xbord9\\org(960,540)}Sized",
    )
  })

  test("leaves an event with no override tags byte-identical", () => {
    expect(getEventTexts(scaleTo1080())[5]).toBe(
      "Plain dialogue with no tags",
    )
  })

  test("scales style geometry on the correct axis and rounds margins", () => {
    const styleRow = getStyleRow(scaleTo1080(), "Default")
    expect(styleRow?.Fontsize).toBe("67.5")
    expect(styleRow?.Outline).toBe("4.5")
    expect(styleRow?.Shadow).toBe("2.25")
    expect(styleRow?.MarginV).toBe("34")
    expect(styleRow?.Spacing).toBe("6")
    expect(styleRow?.MarginL).toBe("30")
    expect(styleRow?.MarginR).toBe("30")
  })

  test("leaves every non-geometric style field alone", () => {
    const styleRow = getStyleRow(scaleTo1080(), "Default")
    expect(styleRow?.Fontname).toBe("Calibri")
    expect(styleRow?.PrimaryColour).toBe("&H00FFFFFF")
    expect(styleRow?.Bold).toBe("0")
    expect(styleRow?.Alignment).toBe("2")
    expect(styleRow?.ScaleX).toBe("100")
    expect(styleRow?.Encoding).toBe("0")
  })

  test("isScalingPositionTags:false leaves every event text alone", () => {
    const texts = getEventTexts(
      scaleTo1080({ isScalingPositionTags: false }),
    )
    expect(texts[0]).toBe("{\\pos(319,450)}Preta Quoiz")
    expect(
      getStyleRow(
        scaleTo1080({ isScalingPositionTags: false }),
        "Default",
      )?.Fontsize,
    ).toBe("67.5")
  })

  test("isScalingStyleGeometry:false leaves every style row alone", () => {
    const result = scaleTo1080({
      isScalingStyleGeometry: false,
    })
    expect(getStyleRow(result, "Default")?.Fontsize).toBe(
      "30",
    )
    expect(getStyleRow(result, "Default")?.MarginV).toBe(
      "15",
    )
    expect(getEventTexts(result)[0]).toBe(
      "{\\pos(957,1012.5)}Preta Quoiz",
    )
  })

  test("ignoredStyleNamesRegexString protects a style row from scaling", () => {
    const result = scaleTo1080({
      ignoredStyleNamesRegexString: "^Nameplate$",
    })
    expect(getStyleRow(result, "Nameplate")?.Fontsize).toBe(
      "30",
    )
    expect(getStyleRow(result, "Nameplate")?.MarginV).toBe(
      "60",
    )
    expect(getStyleRow(result, "Default")?.Fontsize).toBe(
      "67.5",
    )
  })

  // A protected style still has to land where it was drawn, so the guard
  // covers style rows and deliberately not the coordinate tags.
  test("a protected style still gets its position tags scaled", () => {
    expect(
      getEventTexts(
        scaleTo1080({
          ignoredStyleNamesRegexString: "^Nameplate$",
        }),
      )[0],
    ).toBe("{\\pos(957,1012.5)}Preta Quoiz")
  })

  test("a rule whose `from` guard misses changes nothing at all", () => {
    const result = applyAssRules({
      assFile: parseAssFile(SAMPLE_POSITIONED),
      rules: [
        {
          type: "scaleResolution",
          from: { width: 1280, height: 720 },
          to: { width: 1920, height: 1080 },
        },
      ],
    })
    expect(getEventTexts(result)[0]).toBe(
      "{\\pos(319,450)}Preta Quoiz",
    )
    expect(getStyleRow(result, "Default")?.Fontsize).toBe(
      "30",
    )
  })

  test("scaling to the same resolution is a no-op", () => {
    const result = applyAssRules({
      assFile: parseAssFile(SAMPLE_POSITIONED),
      rules: [
        {
          type: "scaleResolution",
          to: { width: 640, height: 480 },
        },
      ],
    })
    expect(getEventTexts(result)[0]).toBe(
      "{\\pos(319,450)}Preta Quoiz",
    )
    expect(getStyleRow(result, "Default")?.Fontsize).toBe(
      "30",
    )
  })
})

describe("applyAssRules — setStyleFields", () => {
  test("changes MarginL, MarginR, MarginV on all non-skipped styles (sample 1: 10,10,18 → 200,200,90)", () => {
    const parsed = parseAssFile(SAMPLE_1)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setStyleFields",
          ignoredStyleNamesRegexString:
            "signs?|op|ed|opening|ending",
          fields: {
            MarginL: "200",
            MarginR: "200",
            MarginV: "90",
          },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    if (section?.sectionType !== "formatted") return

    const defaultStyle = section.entries.find(
      (entry) =>
        entry.entryType === "Style" &&
        entry.fields.Name === "Default",
    )
    expect(defaultStyle?.fields.MarginL).toBe("200")
    expect(defaultStyle?.fields.MarginR).toBe("200")
    expect(defaultStyle?.fields.MarginV).toBe("90")
  })

  test("changes MarginL, MarginR, MarginV on all non-skipped styles (sample 2: 10,10,20 → 200,200,90)", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setStyleFields",
          ignoredStyleNamesRegexString:
            "signs?|op|ed|opening|ending",
          fields: {
            MarginL: "200",
            MarginR: "200",
            MarginV: "90",
          },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    if (section?.sectionType !== "formatted") return

    const defaultStyle = section.entries.find(
      (entry) =>
        entry.entryType === "Style" &&
        entry.fields.Name === "Default",
    )
    expect(defaultStyle?.fields.MarginL).toBe("200")
    expect(defaultStyle?.fields.MarginR).toBe("200")
    expect(defaultStyle?.fields.MarginV).toBe("90")
  })

  test("skips the Signs style when skipNamePattern matches", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setStyleFields",
          ignoredStyleNamesRegexString:
            "signs?|op|ed|opening|ending",
          fields: {
            MarginL: "200",
            MarginR: "200",
            MarginV: "90",
          },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    if (section?.sectionType !== "formatted") return

    const signsStyle = section.entries.find(
      (entry) =>
        entry.entryType === "Style" &&
        entry.fields.Name === "Signs",
    )
    expect(signsStyle?.fields.MarginL).toBe("10")
    expect(signsStyle?.fields.MarginR).toBe("10")
    expect(signsStyle?.fields.MarginV).toBe("20")
  })

  test("applies all fields to Flashback style (not skipped)", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setStyleFields",
          ignoredStyleNamesRegexString:
            "signs?|op|ed|opening|ending",
          fields: {
            MarginL: "200",
            MarginR: "200",
            MarginV: "90",
          },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    if (section?.sectionType !== "formatted") return

    const flashback = section.entries.find(
      (entry) =>
        entry.entryType === "Style" &&
        entry.fields.Name === "Flashback",
    )
    expect(flashback?.fields.MarginV).toBe("90")
  })

  test("applies to all styles when skipNamePattern is not set", () => {
    const parsed = parseAssFile(SAMPLE_2)
    const result = applyAssRules({
      assFile: parsed,
      rules: [
        {
          type: "setStyleFields",
          fields: { MarginV: "90" },
        },
      ],
    })

    const section = result.sections.find(
      (section) => section.sectionName === "V4+ Styles",
    )
    if (section?.sectionType !== "formatted") return

    section.entries.forEach((entry) => {
      if (entry.entryType !== "Style") return
      expect(entry.fields.MarginV).toBe("90")
    })
  })
})
