export const AUDIO_CONVERTED_FOLDER_NAME =
  "AUDIO-CONVERTED" as const
export const AUDIO_OFFSETS_FOLDER_NAME =
  "AUDIO-OFFSETS" as const
export const EXTRACTED_SUBTITLES_FOLDER_NAME =
  "EXTRACTED-SUBTITLES" as const
export const LANGUAGE_TRIMMED_FOLDER_NAME =
  "LANGUAGE-TRIMMED" as const
export const REORDERED_TRACKS_FOLDER_NAME =
  "REORDERED-TRACKS" as const
export const REPLACED_ATTACHMENTS_FOLDER_NAME =
  "REPLACED-ATTACHMENTS" as const
export const REPLACED_TRACKS_FOLDER_NAME =
  "REPLACED-TRACKS" as const
export const SPLITS_FOLDER_NAME = "SPLITS" as const
export const SUBTITLED_FOLDER_NAME = "SUBTITLED" as const
